import type { Metadata } from 'next'
import {
  Geist,
  Geist_Mono,
  Noto_Sans,
  Playfair_Display,
} from 'next/font/google'
import './globals.css'
import { cn } from '@/shared/lib/utils'

const playfairDisplayHeading = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-heading',
})

const notoSans = Noto_Sans({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { SiteFooter } from '@/components/layout/site-footer'
import { SiteHeader } from '@/components/layout/site-header'
import { ClientProviders } from '@/providers/client-providers'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'font-sans',
        notoSans.variable,
        playfairDisplayHeading.variable,
      )}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ClientProviders>
          <SiteHeader />
          <main className="flex-1">{children}</main>
          <SiteFooter />
        </ClientProviders>
      </body>
    </html>
  )
}
